---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-dev
spec:
  goTemplate: true
  goTemplateOptions:
    - "missingkey=error"
  generators:
    - matrix:
        generators:
          - clusters: {}
          - git:
              repoURL: 'https://github.com/sunilkumar2025-dev/argo-rancher.git'
              revision: 'main'
              directories:
                - path: 'apps/*'
  template:
    metadata:
      name: 'dev'
      labels:
        com.apps/environment: 'dev'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: '.'
    spec:
      project: 'default'
      source:
        repoURL: 'https://github.com/sunilkumar2025-dev/argo-rancher.git'
        targetRevision: 'main'
        path: 'apps/*/*'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - values.yaml
            - values-dev.yaml
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: dev
      syncPolicy:    
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
