name: Update Image Tag

on:
    workflow_dispatch:
        inputs:
            project-name:
                description: 'Project name'
                required: true
                default: 'acd'
            environment:
                description: 'Environment name'
                required: true
                default: 'dev'
            image-name:
                description: 'Image name'
                required: true
                default: 'gcr.io/staging-195400/acd'
            new-tag:
                description: 'New image tag'
                required: true
                default: ""
jobs:
  update-image-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: imranismail/setup-kustomize@v2
      - run: |
          git config user.name "sunilkumar2025-dev"
          git config user.email "sunilkumarmsn2025@gmail.com"
          ls -al
          cd argo-kustomize/${{ github.event.inputs.project-name }}/overlays/${{ github.event.inputs.environment }}/
          kustomize edit set image ${{ github.event.inputs.image-name }}=${{ github.event.inputs.new-tag }}
          git add kustomization.yaml
          git commit -m "Set image tag to ${GITHUB_SHA}"
          git push